RNN scratch
ValueError: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([500])) is deprecated. Please ensure they have the same size.